package src;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Polygon;
import java.awt.PopupMenu;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Rectangle2D;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.ListModel;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Luis Benitez
 */
public class ContruccionRNA extends javax.swing.JFrame {

    Image imgFondo;
    FigurasGeometricas figura = new FigurasGeometricas();
    DefaultListModel JList = new DefaultListModel();
    Interfaz interfaz = new Interfaz();

    public ContruccionRNA() {
//        imgFondo = new ImageIcon(getClass().getResource("/src/fondo.gif")).getImage();

        initComponents();

//        fondo.setIcon(new ImageIcon(imgFondo.getScaledInstance(PanelFondo.getWidth(),
//                PanelFondo.getHeight(), Image.SCALE_DEFAULT)));
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    private void MostrarPreview() {

        Graphics grafico = PanelDibujo.getGraphics();
        Graphics2D g2d = (Graphics2D) grafico;

        Rectangle2D rectangulo;
        Ellipse2D elipse;
        Polygon poligono;

        switch (ListaFormas.getSelectedValue()) {
            case "Cuadradro":
                rectangulo = figura.Cuadrado();
                g2d.draw(rectangulo);
                PanelDibujo.paintComponents(g2d);

                break;
            case "Rectangulo":
                rectangulo = figura.Rectangulo();
                g2d.draw(rectangulo);
                PanelDibujo.paintComponents(g2d);
                break;
            case "Elipse":
                elipse = figura.Elipse();
                g2d.draw(elipse);
                PanelDibujo.paintComponents(g2d);
                break;
            case "Circulo":
                elipse = figura.Circulo();
                g2d.draw(elipse);
                PanelDibujo.paintComponents(g2d);
                break;
            case "Triangulo":
                poligono = figura.Tringulo();
                g2d.drawPolygon(poligono);
                PanelDibujo.paintComponents(g2d);
                break;
            case "Trapecio":
                poligono = figura.Trapecio();
                g2d.drawPolygon(poligono);
                PanelDibujo.paintComponents(g2d);
                break;
            case "Hexagono":
                poligono = figura.Hexagono();
                g2d.drawPolygon(poligono);
                PanelDibujo.paintComponents(g2d);
                break;
            /*case "Pentagono":
                poligono = figura.Hexagono();
                g2d.drawPolygon(poligono);
                PanelDibujo.paintComponents(g2d);
                break;
            case "Romboide":
                poligono = figura.Hexagono();
                g2d.drawPolygon(poligono);
                PanelDibujo.paintComponents(g2d);
                break;*/
            default:

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        fondo = new javax.swing.JLabel();
        PanelComponentes = new javax.swing.JPanel();
        PanelDibujo = new javax.swing.JPanel();
        btnAgregar1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        PanelMenu = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaFormas = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        javax.swing.GroupLayout PanelFondoLayout = new javax.swing.GroupLayout(PanelFondo);
        PanelFondo.setLayout(PanelFondoLayout);
        PanelFondoLayout.setHorizontalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 314, Short.MAX_VALUE))
        );
        PanelFondoLayout.setVerticalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 247, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Construccion de RNA");
        setAlwaysOnTop(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelDibujo.setBackground(new java.awt.Color(255, 255, 255));
        PanelDibujo.setMaximumSize(new java.awt.Dimension(200, 200));
        PanelDibujo.setMinimumSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout PanelDibujoLayout = new javax.swing.GroupLayout(PanelDibujo);
        PanelDibujo.setLayout(PanelDibujoLayout);
        PanelDibujoLayout.setHorizontalGroup(
            PanelDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelDibujoLayout.setVerticalGroup(
            PanelDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        btnAgregar1.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        btnAgregar1.setText("Listo");
        btnAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar1ActionPerformed(evt);
            }
        });

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ListaFormas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ListaFormas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Circulo", "Elipse", "Cuadradro", "Rectangulo", "Triangulo", "Trapecio", "Hexagono" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListaFormas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListaFormasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(ListaFormas);

        jScrollPane3.setViewportView(jList1);

        javax.swing.GroupLayout PanelMenuLayout = new javax.swing.GroupLayout(PanelMenu);
        PanelMenu.setLayout(PanelMenuLayout);
        PanelMenuLayout.setHorizontalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        PanelMenuLayout.setVerticalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelComponentesLayout = new javax.swing.GroupLayout(PanelComponentes);
        PanelComponentes.setLayout(PanelComponentesLayout);
        PanelComponentesLayout.setHorizontalGroup(
            PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelComponentesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(PanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelComponentesLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(114, 114, 114))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelComponentesLayout.createSequentialGroup()
                        .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnAgregar1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(PanelDibujo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(49, 49, 49))))
        );
        PanelComponentesLayout.setVerticalGroup(
            PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelComponentesLayout.createSequentialGroup()
                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelComponentesLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(PanelDibujo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jButton1)
                        .addGap(59, 59, 59)
                        .addComponent(btnAgregar1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PanelComponentesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(PanelComponentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListaFormasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListaFormasValueChanged
        if (evt.getValueIsAdjusting()) {
            PanelDibujo.repaint();
        } else {
            MostrarPreview();

        }

    }//GEN-LAST:event_ListaFormasValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String Agregar = ListaFormas.getSelectedValue();
        JList.addElement(Agregar);
        jList1.setModel(JList);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar1ActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz(JList).setVisible(true);
            }
        });

    }//GEN-LAST:event_btnAgregar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContruccionRNA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContruccionRNA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContruccionRNA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContruccionRNA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContruccionRNA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListaFormas;
    private javax.swing.JPanel PanelComponentes;
    private javax.swing.JPanel PanelDibujo;
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JButton btnAgregar1;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
